// work.js

import Head from 'next/head'
import Layout from '../components/layout'
import Description from '../components/description'
import ClientList from '../components/clientList'
import Hero from '../components/hero'

import { createClient } from 'contentful'

const spaceId = process.env.CONTENTFUL_SPACE_ID;
const contentfulAccessKey = process.env.CONTENTFUL_ACCESS_KEY;

export async function getStaticProps() {
  const client = createClient({
    space: spaceId,
    accessToken: contentfulAccessKey,
  });
  const clientRes = await client.getEntries({ content_type: 'client' });

  return {
    props: { clientProps: clientRes.items },
  };

}

export default function Work({ clientProps }) {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero 
        title="Work"
      />
      <Description 
        title="Our Work"
        description="A common theme in our work is content we’re passionate about and creating opportunities to bring people together."        border={ true }
      />
      <ClientList
        width="2"
        clientProps={clientProps}
      />
    </Layout>
  )
}
